author: Zeng Guangtao

keywords: Hexo, Theme-AD

description: Chaos_Site

# 导航栏头部名称
nav_name: Chaos

# 导航栏座右铭
motto: "Something for blogs"

github: "https://github.com/ChaosCodes/"

# 站点图标和APP图标
favicon: 
  icon: /images/favicon.ico
  touch_icon: /images/touch-icon.png

# RSS文件位置
rss: 

# 自定义样式文件位置
custom_style: 

# 代码高亮主题
highlight_theme: "night eighties"

# 开启数学公式渲染
mathjax: true

copyright:
  enable: true
  author: "曾广韬"
  show_link: true
  more: '版权声明: 本博客所有文章除特别声明外, 均采用 <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a> 许可协议. 转载请注明出处!'

# 建站时间. 格式：YYYY-MM-DD
start_time: "2018-02-27"

# 如何开启 评论&统计 插件：https://godbmw.com/passages/2018-11-15-theme-bmw-docs-zh/
# 请申请自己的 appid 和 appkey，并且替换下面的 appid 和 appkey
leancloud:
  appid: 30aez2Xj5kLeavizPUYvJTxY-gzGzoHsz # 填写您的appid
  appkey: mF5hceF2SeM6mArzNCvH2KfD # 填写您的appkey
  comment: true # 是否开启评论系统
  count: false # 是否开启文章统计

# 需要保证leancloud.comment为true
welcome: 
  enable: true
  interval: 30

# 存放sha256加密的密码
# 拥有所有加锁文章的阅读权限
passwords: 
  - efe07af7441da2b69c4a41e42e73be4db47f66010a56900788a458354a7373ec # godbmw

share:
  twitter: true
  facebook: true
  weibo: true
  qq: true
  wechat: true

analytics:
  baidu:
    enable: false
  google:
    enable: false
    id: 


reward:
  -
    src: /images/wechat.png
    alt: "WeChat"
  -
    src: /images/alipay.png
    alt: "AliPay"

nav:
  -
    name: "首页"
    path: "/"
  -
    name: "归档"
    path: "/archives/"

footer:
  -
    title: "相关推荐学习网站"
    children: 
      -
        name: "couresa"
        path: "https://www.coursera.org/"

footer_contact: "Email: kids937@foxmail.co"
